name:                graft
version:             0.1.0.0
github:              "BrianHicks/graft"
license:             BSD3
author:              "Brian Hicks"
maintainer:          "brian@brianthicks.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/BrianHicks/graft#readme>

dependencies:
- base >= 4.7 && < 5
- directory == 1.3.0.2
- fgl == 5.5.4.0
- filepath == 1.4.1.2
- flow == 1.0.10
- Glob == 0.9.1
- pathwalk == 0.3.1.2
- text == 1.2.2.2

library:
  source-dirs: src

default-extensions:
- OverloadedStrings

executables:
  graft:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graft

tests:
  graft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graft
